project_id = "fdllddffiihycbtgawbr"

[functions.departments]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.cleanup-cancelled-appointments]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.send-lab-results-notification]
verify_jwt = false
